# Generated by Django 4.1 on 2022-08-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_users_last_login_users_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created',
        ),
    ]
