# Generated by Django 4.1 on 2022-08-22 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='wallpapers/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image_uuid', models.ForeignKey(db_column='image_uuid', on_delete=django.db.models.deletion.CASCADE, to='main.images')),
            ],
        ),
        migrations.CreateModel(
            name='ImProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('tags', models.JSONField()),
                ('image_uuid', models.ForeignKey(db_column='image_uuid', on_delete=django.db.models.deletion.CASCADE, to='main.images')),
            ],
        ),
    ]
