# Generated by Django 4.1 on 2022-08-15 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="improperties",
            name="image_uuid",
            field=models.ForeignKey(
                db_column="image_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.images",
            ),
        ),
        migrations.AlterField(
            model_name="imstatistics",
            name="image_uuid",
            field=models.ForeignKey(
                db_column="image_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.images",
            ),
        ),
    ]
