# Generated by Django 4.1 on 2022-08-17 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_images_user_id_alter_improperties_image_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("registration_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="images",
            name="user_id",
        ),
        migrations.AddField(
            model_name="images",
            name="user_uuid",
            field=models.ForeignKey(
                db_column="user_uuid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.users",
            ),
        ),
    ]
