# Generated by Django 4.1 on 2022-08-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_users_remove_images_user_id_images_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="user_uuid",
        ),
        migrations.AddField(
            model_name="images",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
