# Generated by Django 4.1 on 2022-08-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_users_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_imtags_remove_images_user_id_images_owner_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='owner_ids',
        ),
        migrations.RemoveField(
            model_name='improperties',
            name='height',
        ),
        migrations.RemoveField(
            model_name='improperties',
            name='width',
        ),
        migrations.AddField(
            model_name='images',
            name='stat',
            field=models.ManyToManyField(through='main.UserImStat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ImStatistics',
        ),
        migrations.AddField(
            model_name='userimstat',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.images'),
        ),
        migrations.AddField(
            model_name='userimstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
